/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Interfaz.matrizLU.orden;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import org.apache.commons.math3.linear.RealMatrix;

/**
 *
 * @author Andres
 */
public class MatricesLURespuesta extends javax.swing.JFrame {
    public double [][] MatrizU;
    public double [][] MatrizL;
    List<JTextField> lista= new ArrayList<>();
    /**
     * Creates new form MatricesLURespuesta
     */
    public MatricesLURespuesta() {
        initComponents();
    }

    public MatricesLURespuesta(RealMatrix MatrizU, RealMatrix MatrizL) {
        initComponents();
        this.getContentPane().setBackground(new Color(20,138,156));
        this.MatrizU = MatrizU.getData();
        this.MatrizL = MatrizL.getData();
        generarMatricesU();
        generarMatricesL();
    }
    
    
    public void generarMatricesU() {
        int contadorFilas1 = 1;
        int contadorColumnas1 = 1;
        int x = 20;
        int y = 40;
        while (contadorFilas1 <= orden) {
            if (contadorColumnas1 <= orden) {
                JTextField entrada1 = new JTextField();
                entrada1.setName("Matriz U " + contadorFilas1 + contadorColumnas1);
                entrada1.setText(Double.toString(MatrizU [contadorFilas1 - 1][contadorColumnas1 - 1]));
                JpanelU.add(entrada1);
                entrada1.setBounds(x, y, 60, 40);
                entrada1.setEnabled(false);
                x += 60;
                contadorColumnas1++;
            } else {
                contadorColumnas1 = 1;
                y += 40;
                x = 20;
                contadorFilas1++;
            }
        }
    }
        
    public void generarMatricesL() {
        int contadorFilas1 = 1;
        int contadorColumnas1 = 1;
        int x = 20;
        int y = 40;
        while (contadorFilas1 <= orden) {
            if (contadorColumnas1 <= orden) {
                JTextField entrada1 = new JTextField();
                entrada1.setName("Matriz L" + contadorFilas1 + contadorColumnas1);
                entrada1.setText(Double.toString(MatrizL [contadorFilas1 - 1][contadorColumnas1 - 1]));
                JpanelL.add(entrada1);
                entrada1.setBounds(x, y, 60, 40);
                entrada1.setEnabled(false);
                x += 60;
                contadorColumnas1++;
            } else {
                contadorColumnas1 = 1;
                y += 40;
                x = 20;
                contadorFilas1++;
            }
        }
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelU = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        JpanelL = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpanelU.setBackground(new java.awt.Color(20, 138, 156));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Matriz U");

        javax.swing.GroupLayout JpanelULayout = new javax.swing.GroupLayout(JpanelU);
        JpanelU.setLayout(JpanelULayout);
        JpanelULayout.setHorizontalGroup(
            JpanelULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelULayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        JpanelULayout.setVerticalGroup(
            JpanelULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        JpanelL.setBackground(new java.awt.Color(20, 138, 156));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Matriz L");

        javax.swing.GroupLayout JpanelLLayout = new javax.swing.GroupLayout(JpanelL);
        JpanelL.setLayout(JpanelLLayout);
        JpanelLLayout.setHorizontalGroup(
            JpanelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLLayout.createSequentialGroup()
                .addGroup(JpanelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(JpanelLLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        JpanelLLayout.setVerticalGroup(
            JpanelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(JpanelU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpanelL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        matrizLU atras = new matrizLU(orden);
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatricesLURespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatricesLURespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatricesLURespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatricesLURespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatricesLURespuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel JpanelL;
    private java.awt.Panel JpanelU;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
