package Interfaz;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.commons.math3.linear.*;

/**
 *
 * @author davidmatafernandez
 */
public class matrizLU extends javax.swing.JFrame {
    public static int orden;
    List<JTextField> lista= new ArrayList<>();
    public static double[][] LU;
    public static int m, n;
    public static int pivsign;
    public static int[] piv;
    //public static int ancho=40;
    //public static int alto=40;
    /**
     * Creates new form matrizLU
     */
    public matrizLU(int cantidad) {
        orden=cantidad;
        initComponents();
        this.getContentPane().setBackground(new Color(20,138,156));
        generarMatrices();
    }
    
    public void generarMatrices() {
        int contadorFilas1 = 1;
        int contadorColumnas1 = 1;
        int x = 20;
        int y = 40;
        while (contadorFilas1 <= orden) {
            if (contadorColumnas1 <= orden) {
                JTextField entrada = new JTextField();
                entrada.setName("Entrada" + contadorFilas1 + contadorColumnas1);
                panelMatriz.add(entrada);
                lista.add(entrada);
                entrada.setBounds(x, y, 60, 40);
                x += 60;
                //ancho+=60;
                contadorColumnas1++;
            } else {
                contadorColumnas1 = 1;
                y += 40;
                x = 20;
//                ancho+=60;
//                alto+=60;
                contadorFilas1++;
            }
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMatriz = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMatriz.setBackground(new java.awt.Color(20, 138, 156));

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jButton1.setText("Generar Matrices LU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Ingrese los datos en la matriz");

        javax.swing.GroupLayout panelMatrizLayout = new javax.swing.GroupLayout(panelMatriz);
        panelMatriz.setLayout(panelMatrizLayout);
        panelMatrizLayout.setHorizontalGroup(
            panelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatrizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelMatrizLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelMatrizLayout.setVerticalGroup(
            panelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(panelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            for (JTextField f : lista) {
                if (f.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Debe completar todos los datos");
                    f.requestFocus();
                    return;
                }
            }
            int contadorFilas = 1;
            int contadorColumnas = 1;
            double [][] normal = new double[orden][orden];
            while (contadorFilas <= orden) {
                if (contadorColumnas <= orden) {
                    for (JTextField f : lista) {
                        if (f.getName().equals("Entrada" + contadorFilas + contadorColumnas)) {
                            normal[contadorFilas - 1][contadorColumnas - 1] = Float.parseFloat(f.getText());
                            contadorColumnas++;
                            break;
                        }
                    }
                } else {
                    contadorFilas++;
                    contadorColumnas = 1;
                }
            }
            System.out.println("Original:"+Arrays.deepToString(normal));
            RealMatrix matriz = MatrixUtils.createRealMatrix(normal);
            RealMatrix L = new LUDecomposition(matriz).getL();
            RealMatrix U = new LUDecomposition(matriz).getU();
            if (L != null && U != null){
                MatricesLURespuesta respuesta = new MatricesLURespuesta(U,L);
                respuesta.setVisible(true);
                this.dispose();
                System.out.println(L);
                System.out.println(U);
            }
            else{
                JOptionPane.showMessageDialog(null, "La matriz es singular por lo tanto no se puede factorizar");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
        
        
        
        
        
        
       
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matrizLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matrizLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matrizLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matrizLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matrizLU(orden).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelMatriz;
    // End of variables declaration//GEN-END:variables
}
